[package]
name = "rgsw"
version = "0.1.0"
authors = ["haslersn <sebastian.hasler@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
uint = "0.8.3"
rand = "0.7.3"
